apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubactions-aks-hajar
spec:
  selector:
    matchLabels:
      app: githubactions-aks-hajar
  template:
    metadata:
      labels:
        app: githubactions-aks-hajar
    spec:
      containers:
      - name: githubactions-aks-hajar
        image: wannabeegeek/githubactions-aks-hajar
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
