apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloppucluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloppucluster
  template:
    metadata:
      labels:
        app: helloppucluster
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: helloppucluster
          image: hajaraburmeileh/hello:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi


---
apiVersion: v1
kind: Service
metadata:
  name: helloppucluster
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: helloppucluster