# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# test
name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: main 
  pull_request:
    branches: main 
permissions:
        id-token: write
        contents: read

jobs:

  Docker:
    name: build image and publish
    runs-on: ubuntu-latest
    env:
      env-file: my-environment-file.env
      CLUSTER_NAME: pwGen
      RESOURSE_GROUP: SWE
      

      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
         java-version: 18
      - name: Build with Maven
        run: mvn -B clean package
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker image
        run: docker build -t hajaraburmeileh/simplecalculator2:${{ github.sha }} -t hajaraburmeileh/simplecalculator2:latest .
      - name: Publish Docker image
        run: docker push hajaraburmeileh/simplecalculator2 --all-tags
             
      - uses: actions/checkout@v3
      - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        name: Azure login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - uses: azure/use-kubelogin@v1
        name: Set up kubelogin for non-interactive login
        with:
          kubelogin-version: v0.0.25
      - uses: azure/aks-set-context@v3
        name: Get K8s context
        with:
          admin: "false"
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.RESOURSE_GROUP }}
          use-kubelogin: "true"
          
      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            kubernetes/deploy.yml
          images: |
            hajaraburmeileh/simplecalculator2:${{ github.sha }}